language: node_js
node_js:
  - "stable"
  - "lts/*"
  - "10.10"
cache:
  directories:
    - client/node_modules
before_install:
  - npm i -g npm@6.4.1
before_script:
  - cd client
script:
  - npm test
  - npm run build
